# Generated by Django 5.2.4 on 2025-08-01 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_uniquecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shrinkinstancemodel',
            name='shrinked_url',
            field=models.URLField(null=True, unique=True),
        ),
    ]
